name: flow1
run-name: 我是因為 ${{ github.event.workflow_run.head_branch }} build完才啟動的，他的版號是 ${{ github.event.workflow_run.run_number }}
on:
  workflow_run:
    workflows: ["feature-build"]
    types:
      - completed
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!